### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [sylyu/rocketpop#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by sylyu** [comment]
I added the mobile meta tag in the header of application.html.erb and the
about page alignment looks much better, however the font is looks too big.

Sylvia

**Comment by sylyu** [comment]
Reduced font size for h1, h2 and h2 span in master.css.scss to 38px file.
